# Generated by Django 5.0.4 on 2024-07-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_record_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='creator',
        ),
    ]
